#
# Makefile for cc65 samples (io2)
#
# This Makefile requires GNU make
#

.PHONY:	all
all: \
	bgcol1.jb \
	bgcol2.jb \
	idummy.jb \
	iload.jb \
	ipnggen1.jb \
	ipnggen2.jb \
	ipnggen3.jb \
	resize.jb \
	setpal.jb \
	stdpal.jb

include ../Samples.mk
