#
# Makefile for cc65 samples (io2)
#
# This Makefile requires GNU make
#

all:
	( cd 6502 ; make all )
	( cd io1 ; make all )
	( cd io2 ; make all )
	( cd extra ; make all )

clean:
	( cd 6502 ; make clean )
	( cd io1 ; make clean )
	( cd io2 ; make clean )
	( cd extra ; make clean )
