#
# Makefile for cc65 samples (io2)
#
# This Makefile requires GNU make
#

.PHONY:	all
all: \
	bounce.jb \
	cciao.jb \
	clock.jb \
	cpubm.jb \
	dpyinfo.jb \
	fps.jb \
	gperf.jb \
	hello.jb \
	mandelbrot.jb \
	newline.jb \
	pngtest.jb \
	rand.jb \
	time.jb \
	smile.jb \
	bounce.prg \
	cpubm.prg

include ../Samples.mk
