#
# Makefile for cc65 samples (io2)
#
# This Makefile requires GNU make
#

.PHONY:	all
all: \
	gamekeys.jb \
	irawrgba.jb \
	maze.jb \
	sprites.jb \
	template.jb \
	tiles.jb \
	vintage.jb

include ../Samples.mk
